### ISSUE TITLE
when I run the train_and_save.py,I got this error

### ISSUE THREAD

**Issue by eai2x** [guillaume-chevalier/LSTM-Human-Activity-Recognition#34]
Traceback (most recent call last):
  File "D:/GraduationCode/LSTM-HAR-latest/train_and_save.py", line 11, in <module>
    from neuraxle_tensorflow.tensorflow_v1 import TensorflowV1ModelStep
ModuleNotFoundError: No module named 'neuraxle_tensorflow'

Thanks.

**Comment by eai2x** [comment]
yes,I konw,please download this first.https://github.com/Neuraxio/Neuraxle-TensorFlow

**Comment by guillaume-chevalier** [comment]
Yes, you can [`pip install neuraxle-tensorflow`](https://github.com/Neuraxio/Neuraxle-TensorFlow).

**Comment by eai2x** [comment]
@guillaume-chevalier Your method works, thank you for your reply.

I have been troubled by new errors these days and haven't found a solution. If you have time, can you check it for me? I just want to save the model and use it.Is it because I downloaded the wrong file train_and_save.py? I use the version of it from [here](https://github.com/guillaume-chevalier/LSTM-Human-Activity-Recognition/pull/32)of Neuraxio:neuraxle-refactor.

Thank you again.

The error is here:
Traceback (most recent call last):

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'TensorflowV1ModelStep/expected_outputs' with dtype float and shape [?,6]
	 [[{{node TensorflowV1ModelStep/expected_outputs}}]]
	 [[TensorflowV1ModelStep/loss/_11]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'TensorflowV1ModelStep/expected_outputs' with dtype float and shape [?,6]
	 [[{{node TensorflowV1ModelStep/expected_outputs}}]]
0 successful operations.
0 derived errors ignored.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\GraduationCode\LSTM-HAR-latest\train_and_save.py", line 165, in <module>
    main()

  File "D:\GraduationCode\LSTM-HAR-latest\train_and_save.py", line 150, in main
    pipeline, outputs = pipeline.fit_transform(data_inputs, expected_outputs)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 681, in fit_transform
    new_self, data_container = self.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\steps\data.py", line 119, in _fit_transform_data_container
    self.wrapped = self.wrapped.handle_fit(data_container.copy(), context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 905, in handle_fit
    new_self = self._fit_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\metaopt\random.py", line 129, in _fit_data_container
    new_self, results_data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\metaopt\random.py", line 144, in _fit_transform_data_container
    self.wrapped, results_data_container = self.wrapped.handle_fit_transform(train_data_container, context.push(self.wrapped))

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1714, in _fit_transform_data_container
    self.wrapped, data_container = self.wrapped.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 488, in handle_fit_transform
    context=context

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 628, in join_fit_transform
    step, data_container_batch = step._fit_transform_data_container(data_container_batch, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1714, in _fit_transform_data_container
    self.wrapped, data_container = self.wrapped.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1016, in _fit_transform_data_container
    new_self, out = self.fit_transform(data_container.data_inputs, data_container.expected_outputs)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1119, in fit_transform
    out = new_self.transform(data_inputs)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle_tensorflow\tensorflow_v1.py", line 160, in transform
    return self.transform_model(data_inputs)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle_tensorflow\tensorflow_v1.py", line 175, in transform_model
    results = self.session.run([self[inference_output_name], self['loss']], feed_dict=feed_dict)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)

  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'TensorflowV1ModelStep/expected_outputs' with dtype float and shape [?,6]
	 [[node TensorflowV1ModelStep/expected_outputs (defined at C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
	 [[TensorflowV1ModelStep/loss/_11]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'TensorflowV1ModelStep/expected_outputs' with dtype float and shape [?,6]
	 [[node TensorflowV1ModelStep/expected_outputs (defined at C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'TensorflowV1ModelStep/expected_outputs':
  File "C:\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\console\start.py", line 318, in main
    kernel.start()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
  File "C:\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "C:\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "C:\anaconda3\envs\tensorflow\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-567c3de76cd6>", line 1, in <module>
    runfile('D:/GraduationCode/LSTM-HAR-latest/train_and_save.py', wdir='D:/GraduationCode/LSTM-HAR-latest')
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 476, in runfile
    exec_code(file_code, filename, ns_globals, ns_locals)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 377, in exec_code
    exec(compile(code, filename, 'exec'), ns_globals, ns_locals)
  File "D:\GraduationCode\LSTM-HAR-latest\train_and_save.py", line 165, in <module>
    main()
  File "D:\GraduationCode\LSTM-HAR-latest\train_and_save.py", line 150, in main
    pipeline, outputs = pipeline.fit_transform(data_inputs, expected_outputs)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 681, in fit_transform
    new_self, data_container = self.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\steps\data.py", line 119, in _fit_transform_data_container
    self.wrapped = self.wrapped.handle_fit(data_container.copy(), context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 905, in handle_fit
    new_self = self._fit_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\metaopt\random.py", line 129, in _fit_data_container
    new_self, results_data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\metaopt\random.py", line 144, in _fit_transform_data_container
    self.wrapped, results_data_container = self.wrapped.handle_fit_transform(train_data_container, context.push(self.wrapped))
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1714, in _fit_transform_data_container
    self.wrapped, data_container = self.wrapped.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 488, in handle_fit_transform
    context=context
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 628, in join_fit_transform
    step, data_container_batch = step._fit_transform_data_container(data_container_batch, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 188, in _fit_transform_data_container
    step, data_container = step.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 1714, in _fit_transform_data_container
    self.wrapped, data_container = self.wrapped.handle_fit_transform(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\base.py", line 922, in handle_fit_transform
    new_self, data_container = self._fit_transform_data_container(data_container, context)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle\pipeline.py", line 187, in _fit_transform_data_container
    step.setup()
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\neuraxle_tensorflow\tensorflow_v1.py", line 87, in setup
    model = self.create_model(self)
  File "D:\GraduationCode\LSTM-HAR-latest\train_and_save.py", line 28, in create_graph
    expected_outputs = tf.placeholder(tf.float32, [None, step.hyperparams['n_classes']], name='expected_outputs')
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
